spring:
  application:
    name: hr_bank

# Railway에서 쓸 환경변수
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} 

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB

  mvc:
    log-request-details: true

# Swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    persist-authorization: true

# Logging
logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.hibernate.type.descriptor.sql: off

    org.springframework.web: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

hr-bank:
  storage:
    type: local
    local:
      root-path: /data/storage
